# Generated by Django 2.2.16 on 2023-02-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230216_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
