# Generated by Django 2.2.16 on 2023-02-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
