# Generated by Django 2.2.16 on 2023-02-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
